Repository onflow/flow-evm-gateway, pull requests merged in 2024-09, with the labels that each got.

#504 Incorrect hash value for empty `sha3Uncles` block field
  api/api.go
  tests/integration_test.go
  tests/web3js/eth_non_interactive_test.js
Labels: Bugfix, EVM

#501 Support more signing algorithms for COA key
  config/config.go
Labels: Improvement, EVM

#505 Increase `batchRequestLimit` and `batchResponseMaxSize` constants
  api/server.go
  tests/web3js/eth_non_interactive_test.js
Labels: Improvement, EVM

#500 Improve COA creation transaction to gracefully handle existing COA in storage
  services/requester/cadence/create_coa.cdc
  services/requester/requester.go
Labels: Improvement, EVM

#498 Handle `ErrHeightOutOfRange` errors in `EstimateGas`
  services/requester/requester.go
Labels: Improvement, EVM

#507 Filter out errors for missing endpoints as they are not really relevant
  api/server.go
Labels: Improvement, EVM

#510 Add test cases for endpoint of the `PullAPI`
  api/pull.go
  tests/e2e_web3js_test.go
  tests/helpers.go
  tests/web3js/eth_filter_endpoints_test.js
  tests/web3js/eth_get_filter_logs_test.js
Labels: Improvement, Technical Debt, Testing, EVM

#516 Fix display of duplicate logs
  api/server.go
  services/requester/remote_state.go
Labels: Improvement, Chore, EVM

#527 Crasher on validation of args for `eth_estimateGas`
  api/models.go
  api/models_test.go
  models/transaction_test.go
Labels: Bugfix, EVM

#526 Add an E2E test for filling the EVM state with blocks & transactions
  tests/e2e_web3js_test.go
  tests/web3js/build_evm_state_test.js
  tests/web3js/helpers.js
Labels: Testing, EVM

#532 Fix flaky E2E test for EVM state building
  tests/web3js/build_evm_state_test.js
Labels: Testing, EVM

#536 Update the `storage` solidity contract used in testing
  tests/e2e_web3js_test.go
  tests/fixtures/storage.byte
  tests/fixtures/storage.sol
  tests/fixtures/storageABI.json
  tests/web3js/eth_deploy_contract_and_interact_test.js
  tests/web3js/eth_filter_endpoints_test.js
  tests/web3js/eth_transaction_type_fees_test.js
Labels: Testing, EVM

#533 Response returned from `eth_getBlockReceipts` endpoint is not properly marshalled
  api/api.go
  tests/web3js/eth_non_interactive_test.js
Labels: Bugfix, EVM

#529 Check data integrity for EVM events
  models/events.go
  models/events_test.go
  services/ingestion/engine_test.go
  services/ingestion/subscriber.go
  services/ingestion/subscriber_test.go
  services/testutils/mock_client.go
Labels: Improvement, EVM

#538 Add test cases utilizing Cadence arch calls
  tests/fixtures/storage.byte
  tests/fixtures/storage.sol
  tests/fixtures/storageABI.json
  tests/helpers.go
  tests/web3js/build_evm_state_test.js
  tests/web3js/eth_deploy_contract_and_interact_test.js
  tests/web3js/eth_filter_endpoints_test.js
  tests/web3js/eth_transaction_type_fees_test.js
Labels: Testing, EVM

#548 Block endpoints with many transactions fail with rate limit error
  api/api.go
Labels: Improvement, Bugfix, EVM

#549 Filter-related endpoints return `null` result instead of empty array
  api/pull.go
  tests/web3js/eth_filter_endpoints_test.js
Labels: Improvement, EVM

#557 Fix format for block traces on debug API
  api/debug.go
Labels: Bugfix, EVM

#560 Fix error handling for transaction traces
  api/debug.go
Labels: Bugfix, EVM

#564 Update constant for block gas limit
  api/encode_transaction.go
  tests/web3js/eth_non_interactive_test.js
Labels: Bugfix, EVM

#568 Remove `--evm-enabled` flag in README.md instructions
  README.md
Labels: Documentation

#571 Add metric for indexed cadence block height
  metrics/collector.go
  metrics/nop.go
  services/ingestion/engine.go
Labels: Improvement

#593 Remove obsolete config flags & keys files
  Dockerfile
  README.md
  migration-keys.json
  previewnet-keys.json
Labels: Technical Debt, Documentation

#598 Update CODEOWNERS file
  .github/CODEOWNERS
Labels: Chore
