Repository onflow/flow-evm-gateway, pull requests merged in 2024-10, with the labels that each got.

#600 Refactor engine status
  models/engine.go
  services/ingestion/engine.go
  services/traces/engine.go
Labels: Improvement, EVM

#595 Add block/tx indexed metrics and spork client logging
  metrics/collector.go
  metrics/nop.go
  services/ingestion/engine.go
  services/requester/cross-spork_client.go
  services/requester/cross-spork_client_test.go
Labels: Improvement

#566 Fix `Genesis` block hash calculation for `Testnet` network
  storage/pebble/blocks.go
Labels: Bugfix, EVM

#611 Avoid logging debug info for invalid JSON-RPC methods
  api/api.go
  api/server.go
Labels: Improvement, EVM

#613 Update the list of valid JSON-RPC methods
  api/api.go
Labels: Improvement, EVM

#602 Add generics to subscriber and publisher and fix potential deadlock
  api/stream.go
  bootstrap/bootstrap.go
  go.mod
  models/stream.go
  models/stream_test.go
  services/ingestion/engine.go
  services/ingestion/engine_test.go
  services/requester/pool.go
  services/traces/engine.go
  services/traces/engine_test.go
Labels: Improvement, EVM

#592 Use the released tag version to identify newly-created docker images
  .github/workflows/build.yml
Labels: Improvement, EVM

#615 Add traces backfill option
  README.md
  api/profiler.go
  bootstrap/bootstrap.go
  config/config.go
  services/traces/engine.go
  services/traces/engine_test.go
Labels: Improvement

#617 Reuse block preparation logic in streaming API
  api/stream.go
  bootstrap/bootstrap.go
Labels: Improvement

#619 Fix timeouts from E2E test regarding `eth_subscribe`
  tests/helpers.go
  tests/web3js/eth_streaming_test.js
Labels: Testing

#616 Add CLI commands on binary
  Dockerfile
  Makefile
  README.md
  cmd/main.go
  cmd/main/main.go
  cmd/run/cmd.go
  cmd/version/cmd.go
  config/config.go
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: Improvement, EVM

#614 Add JSON tags in `content` type for proper field serialization in `TxPool` API
  api/pool.go
Labels: EVM, Compatibility

#620 Introduce dedicated `BlockHeader` type for usage in `newHeads` subscription endpoint
  api/models.go
  api/stream.go
  bootstrap/bootstrap.go
  tests/web3js/eth_streaming_test.js
Labels: EVM, Compatibility

#625 Output version info from version command to output channel
  cmd/version/cmd.go
Labels: Bugfix

#622 Sort Flow EVM events received from Event Streaming API by their `TransactionIndex` & `EventIndex` fields in ascending order
  models/events.go
  models/events_test.go
Labels: Improvement, EVM

#632 Implement `BlockSnapshotProvider` & `BlockSnapshot` interfaces
  bootstrap/bootstrap.go
  services/ingestion/engine.go
  services/ingestion/engine_test.go
  services/replayer/blocks_provider.go
  services/replayer/blocks_provider_test.go
  storage/mocks/mocks.go
Labels: Improvement, EVM
