Repository onflow/flow-evm-gateway, pull requests merged in 2025-04, with the labels that each got.

#782 Add a test case to verify correctness of `EVM.dryCall` & `COA.dryCall`
  go.mod
  go.sum
  tests/e2e_web3js_test.go
  tests/go.mod
  tests/go.sum
  tests/web3js/evm_dry_call_test.js
Labels: Testing, EVM

#775 Add a CLI utility to verify integrity of EVM blocks DB
  cmd/blocks/cmd.go
  cmd/main.go
Labels: Regression, EVM

#800 Bump `onflow/flow-go` version with EVM Pectra hard-fork enabled
  go.mod
  go.sum
  models/transaction_test.go
  tests/go.mod
  tests/go.sum
  tests/web3js/build_evm_state_test.js
  tests/web3js/debug_traces_test.js
  tests/web3js/eth_deploy_contract_and_interact_test.js
Labels: EVM

#801 Update to `flow-go` with `go-ethereum@v1.15.4`
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: EVM

#802 Update to `flow-go` with `go-ethereum@v1.15.5`
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: EVM

#806 Update eth_syncing to return false for currentBlock >= highestBlock
  api/api.go
Labels: Bug

#808 Add some E2E tests for `debug_*` endpoints with unset tracer
  api/debug.go
  tests/web3js/debug_traces_test.js
Labels: Testing
