Repository onflow/flow-evm-gateway, pull requests merged in 2025-02, with the labels that each got.

#736 Increase computation limit for Cadence tx
  models/errors/errors.go
  services/requester/requester.go
  tests/web3js/eth_failure_handling_test.js
Labels: Improvement, Performance, EVM

#738 Update `cadence`/`flow-go`/`flow-go-sdk`/`flow-emulator` dependencies
  .github/workflows/ci.yml
  Dockerfile
  api/debug.go
  bootstrap/bootstrap.go
  go.mod
  go.sum
  services/evm/executor.go
  tests/go.mod
  tests/go.sum
  tests/web3js/config.js
  tests/web3js/debug_traces_test.js
  tests/web3js/eth_filter_endpoints_test.js
  tests/web3js/eth_logs_filtering_test.js
  tests/web3js/eth_non_interactive_test.js
  tests/web3js/verify_cadence_arch_calls_test.js
Labels: Chore

#753 Start event ingestion on proper block height when connecting to local Emulator
  bootstrap/bootstrap.go
Labels: Bugfix

#752 Track time taken to fully ingest an EVM block in the local state index
  metrics/collector.go
  metrics/nop.go
  services/ingestion/engine.go
Labels: Improvement

#740 Move recording of available-signing-keys metric inside a deferred function
  Makefile
  api/server.go
  services/requester/requester.go
Labels: Improvement

#747 Refactor metric for request duration
  api/server.go
  metrics/handler.go
Labels: Improvement, Bugfix

#754 Update flow-go dependency to fix tx replay validation
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: Bugfix

#759 Consolidate the validations for max TX gas limit
  api/api.go
  api/debug.go
  api/utils.go
  models/transaction.go
  models/transaction_test.go
  services/requester/requester.go
  tests/web3js/debug_traces_test.js
  tests/web3js/eth_failure_handling_test.js
Labels: Improvement, Technical Debt, EVM

#760 Make ingestion of EVM events idempotent
  api/debug.go
  bootstrap/bootstrap.go
  go.mod
  go.sum
  metrics/collector.go
  storage/pebble/register_storage.go
  tests/go.mod
  tests/go.sum
  tests/integration_test.go
Labels: EVM

#750 Add transaction rate-limit functionality
  api/utils.go
  cmd/run/cmd.go
  config/config.go
  services/requester/requester.go
Labels: Improvement, Performance, EVM

#768 Replace all `internal error` occurrences with actual error messages
  api/api.go
  api/server.go
  api/stream.go
  api/utils.go
  eth/types/types.go
  models/errors/errors.go
  services/requester/key_store.go
Labels: Improvement, Technical Debt

#770 Initialize keys and balance metrics on startup
  services/requester/requester.go
Labels: Improvement
