Repository onflow/flow-evm-gateway, pull requests merged in 2025-03, with the labels that each got.

#772 Fix concurrent map access in keystore
  bootstrap/bootstrap.go
  go.mod
  go.sum
  services/ingestion/event_subscriber.go
  services/ingestion/event_subscriber_test.go
  services/requester/key_store.go
  services/requester/keystore/account_key.go
  services/requester/keystore/key_store.go
  services/requester/keystore/key_store_test.go
  services/requester/requester.go
Labels: Bugfix, Bug

#784 Adjust histogram buckets for block_ingestion_time_seconds metric
  metrics/collector.go
Labels: Improvement

#771 Check system tx if block is missing EVM block events
  Makefile
  bootstrap/bootstrap.go
  go.mod
  go.sum
  services/ingestion/block_tracking_subscriber.go
  services/ingestion/sealing_verifier.go
  services/requester/cross-spork_client.go
  tests/go.mod
  tests/go.sum
Labels: Bug

#785 Update CI actions, and remove cache
  .github/workflows/ci.yml
Labels: Improvement

#790 Allow WebSocket connections in local environment
  Makefile
Labels: Improvement, EVM
