Repository onflow/flow-evm-gateway, pull requests merged in 2025-09, with the labels that each got.

#874 Include `errorCode` from EVM `txResult` in Cadence assert message
  services/requester/cadence/batch_run.cdc
  services/requester/cadence/run.cdc
  services/requester/tx_pool.go
Labels: Improvement, EVM

#881 Bump flow-go version to `v0.43.0`
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: Improvement, EVM

#884 Allow specifying a tag when building images
  .github/workflows/build.yml
Labels: Improvement

#886 Deprecate `--init-cadence-height` CLI flag
  cmd/run/cmd.go
  config/config.go
Labels: Chore, Technical Debt
